### ISSUE TITLE
Different rendering XML, Compose, Web

### ISSUE THREAD

**Issue by timrijckaert** [BMukhtar/linear-gradient-any-angle#2]
Hello, 

I saw your [post](https://medium.com/@bimurat.mukhtar/how-to-implement-linear-gradient-with-any-angle-in-jetpack-compose-3ded798c81f5) and wanted to try out your implementation.

I notice there are differences in rendering between web <-> xml <-> Compose.
Is there a way to consolidate these?

https://codepen.io/diezjietal/pen/MWZQgzw

**Web**

```html
<div class="gradient"></div>
<div class="gradient"></div>
<div class="gradient"></div>
<div class="gradient"></div>
```

```css
.gradient {
	--angle: 0deg;
	display: inline-block;
	width: 300px;
	aspect-ratio: 1;
	background: linear-gradient(var(--angle), red, blue); // red bottom, blue top
}

.gradient:nth-child(2) {
	--angle: 180deg; // red top, blue bottom - same as setting no angle
}

.gradient:nth-child(3) {
	--angle: 90deg; // red left, blue right
}

.gradient:nth-child(4) {
	--angle: 45deg; // red lower left corner, blue upper right corner
}
```

<img width="1215" alt="Screenshot 2023-09-22 at 19 23 17" src="https://github.com/BMukhtar/linear-gradient-any-angle/assets/6739443/8f547bb3-a9a1-482b-9179-d5f29c95a0f1">

**XML**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <gradient
        android:angle="0"
        android:endColor="#ffff0000"
        android:startColor="#ff0000ff" />
</shape>
```
<img width="150" alt="Screenshot 2023-09-22 at 19 24 34" src="https://github.com/BMukhtar/linear-gradient-any-angle/assets/6739443/8b60442f-b7d5-4df8-b76e-1c5938a0bcb6">
<img width="150" alt="Screenshot 2023-09-22 at 19 24 52" src="https://github.com/BMukhtar/linear-gradient-any-angle/assets/6739443/45180b08-6eb7-4689-9f51-9a3edebacee1">
<img width="150" alt="Screenshot 2023-09-22 at 19 25 15" src="https://github.com/BMukhtar/linear-gradient-any-angle/assets/6739443/6acbeafc-b455-4a41-bb3c-33abd6309351">
<img width="150" alt="Screenshot 2023-09-22 at 19 25 35" src="https://github.com/BMukhtar/linear-gradient-any-angle/assets/6739443/84854d19-25ca-4681-bdcf-71989eedae7a">

**Compose**

```kotlin
@Preview(device = Devices.DESKTOP)
@Composable
fun GradientPreview() {
    Column {
        val gradients = listOf(
            Brush.linearGradient(listOf(0F to Color.Red,100F to Color.Blue), 0f),
            Brush.linearGradient(listOf(0F to Color.Red,100F to Color.Blue), 180f),
            Brush.linearGradient(listOf(0F to Color.Red,100F to Color.Blue), 90f),
            Brush.linearGradient(listOf(0F to Color.Red,100F to Color.Blue), 45f),
        )

        LazyRow(modifier = Modifier.fillMaxSize(), horizontalArrangement = Arrangement.spacedBy(16.dp)) {
            items(gradients) {
                Box(
                    modifier = Modifier
                        .size(100.dp)
                        .background(it)
                )
            }
        }
    }
}
```

<img width="897" alt="Screenshot 2023-09-22 at 19 27 11" src="https://github.com/BMukhtar/linear-gradient-any-angle/assets/6739443/81112d3d-964e-43bb-8d4e-adee4abc2e9b">

> I put all of the images in the same order
